package com.pokemon.toronto.game.com.pokemon.toronto.item;

/**
 * Created by gregorykelsie on 2018-02-09.
 */

public enum TmId {
    WORK_UP(1),
    DRAGON_CLAW(2),
    PSYSHOCK(3),
    CALM_MIND(4),
    ROAR(5),
    TOXIC(6),
    HAIL(7),
    BULK_UP(8),
    VENOSHOCK(9),
    HIDDEN_POWER(10),
    SUNNY_DAY(11),
    TAUNT(12),
    ICE_BEAM(13),
    BLIZZARD(14),
    HYPER_BEAM(15),
    LIGHT_SCREEN(16),
    PROTECT(17),
    RAIN_DANCE(18),
    ROOST(19),
    SAFEGUARD(20),
    FRUSTRATION(21),
    SOLAR_BEAM(22),
    SMACK_DOWN(23),
    THUNDERBOLT(24),
    THUNDER(25),
    EARTHQUAKE(26),
    RETURN(27),
    LEECH_LIFE(28),
    PSYCHIC(29),
    SHADOW_BALL(30),
    BRICK_BREAK(31),
    DOUBLE_TEAM(32),
    REFLECT(33),
    SLUDGE_WAVE(34),
    FLAMETHROWER(35),
    SLUDGE_BOMB(36),
    SANDSTORM(37),
    FIRE_BLAST(38),
    ROCK_TOMB(39),
    AERIAL_ACE(40),
    TORMENT(41),
    FACADE(42),
    FLAME_CHARGE(43),
    REST(44),
    ATTRACT(45),
    THIEF(46),
    LOW_SWEEP(47),
    ROUND(48),
    ECHOED_VOICE(49),
    OVERHEAT(50),
    STEEL_WING(51),
    FOCUS_BLAST(52),
    ENERGY_BALL(53),
    FALSE_SWIPE(54),
    SCALD(55),
    FLING(56),
    CHARGE_BEAM(57),
    SKY_DROP(58),
    BRUTAL_SWING(59),
    QUASH(60),
    WILL_O_WISP(61),
    ACROBATICS(62),
    EMBARGO(63),
    EXPLOSION(64),
    SHADOW_CLAW(65),
    PAYBACK(66),
    SMART_STRIKE(67),
    GIGA_IMPACT(68),
    ROCK_POLISH(69),
    AURORA_VEIL(70),
    STONE_EDGE(71),
    VOLT_SWITCH(72),
    THUNDER_WAVE(73),
    GYRO_BALL(74),
    SWORDS_DANCE(75),
    FLY(76),
    PSYCH_UP(77),
    BULLDOZE(78),
    FROST_BREATH(79),
    ROCK_SLIDE(80),
    X_SCISSOR(81),
    DRAGON_TAIL(82),
    INFESTATION(83),
    POISON_JAB(84),
    DREAM_EATER(85),
    GRASS_KNOT(86),
    SWAGGER(87),
    SLEEP_TALK(88),
    U_TURN(89),
    SUBSTITUTE(90),
    FLASH_CANNON(91),
    TRICK_ROOM(92),
    WILD_CHARGE(93),
    SURF(94),
    SNARL(95),
    NATURE_POWER(96),
    DARK_PULSE(97),
    WATERFALL(98),
    DAZZLING_GLEAM(99),
    CONFIDE(100);

    private final int value;
    private TmId(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
